name: Add new token
description: Add token metadata to Hydration apps
title: "Add "
labels: ["add-token"]
projects: []
body:
  - type: input
    id: ticker
    attributes:
      label: Ticker
      description: Add token ticker
    validations:
      required: true
  - type: input
    id: token-id
    attributes:
      label: ID
      description: Hydration token ID
    validations:
      required: true
  - type: textarea
    id: icon
    attributes:
      label: Icon SVG or PNG < 30kb 128x128
      description: Add token icon in png or svg format < 30Kb 
      placeholder: Click here then drag and drop icon.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for submitting new token request.
